[package]
name = "arrow_scalars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "14.0"
tonic = "0.6.2"
prost = "0.9"
half = {version = "1.8.2", features = ["use-intrinsics", "alloc", "std"]}
chrono = "0.4"

[build-dependencies]
tonic-build = "0.6.2"
